"""add column numero to bilhetes table

Revision ID: 7ebaeb26bc4a
Revises: 9b3a4e087fc1
Create Date: 2024-07-13 16:12:10.026427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebaeb26bc4a'
down_revision: Union[str, None] = '9b3a4e087fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bilhetes', sa.Column('numero', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bilhetes', 'numero')
    # ### end Alembic commands ###
