"""create bilhetes table

Revision ID: 9b3a4e087fc1
Revises: 1c6a817b01cb
Create Date: 2024-07-13 10:17:02.391694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3a4e087fc1'
down_revision: Union[str, None] = '1c6a817b01cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bilhetes',
        sa.Column('bilhete_id', sa.Integer(), nullable=False),
        sa.Column('rifa_id', sa.Integer(), nullable=False),
        sa.Column('comprador_id', sa.Integer(), nullable=False),
        sa.Column('preco', sa.Float(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['comprador_id'],
            ['compradores.comprador_id'],
        ),
        sa.ForeignKeyConstraint(
            ['rifa_id'],
            ['rifas.rifa_id'],
        ),
        sa.PrimaryKeyConstraint('bilhete_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilhetes')
    # ### end Alembic commands ###
