"""create bilhetes tables

Revision ID: e17cb167e13b
Revises: a40a3872892e
Create Date: 2024-06-28 09:50:52.377087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17cb167e13b'
down_revision: Union[str, None] = 'a40a3872892e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilhetes',
    sa.Column('bilhete_id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=True),
    sa.Column('vendido', sa.Boolean(), nullable=False, default=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.comprador_id'], ),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.rifa_id'], ),
    sa.PrimaryKeyConstraint('bilhete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilhetes')
    # ### end Alembic commands ###
