"""create rifas tables

Revision ID: ea87152f9ca3
Revises: 74f81d8d56e4
Create Date: 2024-06-28 09:46:21.593609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea87152f9ca3'
down_revision: Union[str, None] = '74f81d8d56e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rifas',
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('criador_id', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_bilhete', sa.Float(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('premio_nome', sa.String(length=50), nullable=False),
    sa.Column('premio_imagem', sa.String(), nullable=False),
    sa.Column('data_sorteio', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('rifa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rifas')
    # ### end Alembic commands ###
